### PR TITLE
Add osx_arm64

### PR DESCRIPTION
**Pull request by AntoinePrv**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by AntoinePrv** [comment]
@conda-forge-admin, please rerender

**Comment by AntoinePrv** [comment]
@conda-forge/help-osx-arm64 how can I enable *native* `osx_arm64` builds? Previous [experiments](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1088134&view=logs&j=d6b58996-039f-5e48-56bf-c3a016e5cd7f&t=dd6a23d9-2356-5264-64bf-579875a5d8d6&l=1654) failed with `Bad CPU type in executable` (the exec being built need to be executed after build to generate metadata files).

I tried to modify `conda-forge.yml`, but re-rendering does not produce anything for `osx_arm64` native.

**Comment by xhochy** [comment]
There are no native `osx_arm64` runners on conda-forge. Everything must be cross-compiled.

**Comment by xhochy** [comment]
The changes in this PR make no difference to how any of the jobs is executed.

**Comment by AntoinePrv** [comment]
Got it! Trying something different

**Pull request merged**
